spring:
  datasource:
    url: jdbc:mysql://localhost/community?serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#Github配置
Github:
  client_id: 2891fa698a9bf3f5843a
  client_secret: 523bb9d8654579f1bc3bcf8a479e9f4470fb92ce
  redirect_uri: http://localhost:6060/callback