spring:
  profiles:
    active: dev

server:
  port: 6060

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: fzb.community.mapper
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    max-size: 20MB
    max-history: 3
    path: ./logs/log.log
  level:
    root: info
